"""empty message

Revision ID: 91d2e077717f
Revises: 3ce557b8a98b
Create Date: 2021-05-11 07:40:50.781521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91d2e077717f'
down_revision = '3ce557b8a98b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('picklist', sa.Column('name_lang', sa.String(length=100), nullable=True))
    op.add_column('picklist', sa.Column('order', sa.Integer(), nullable=True))
    op.add_column('picklist', sa.Column('translate', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('picklist', 'translate')
    op.drop_column('picklist', 'order')
    op.drop_column('picklist', 'name_lang')
    # ### end Alembic commands ###
